#!/usr/bin/env python3
"""
Validate topic_pack quality rules.

This complements scripts/validate_topic_packs.py. The existing validator checks
structural/runtime compatibility. This script checks authoring quality so that a
new scaffold is not accidentally committed as if it were reviewed content.

Checks:
  - required topic pack files exist
  - topic_id fields match directory name
  - no TODO placeholders in reviewed JSON/README files
  - model_answer routing_aliases and routing_field_points are sufficiently rich
  - fact anchors have anchor_id and statement/expected
  - topic_importance has core policy fields
  - logic_check is optional, but if present it must have a valid structure
  - generic routing aliases are reported as warnings by default

Examples:

  python3 scripts/validate_topic_pack_quality.py

  python3 scripts/rubric_manager.py validate-topic-pack-quality

  python3 scripts/rubric_manager.py validate-topic-pack-quality \
    --topic-id second_order_system_resonance_frequency_response \
    --strict-generic-aliases
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


REQUIRED_FILES = [
    "README.md",
    "fact_anchor.json",
    "model_answer.json",
    "topic_importance.json",
]

OPTIONAL_FILES = [
    "logic_check.json",
]

# Only explicit scaffold markers are treated as placeholder text.
# Ordinary Korean verbs such as "작성한다" are valid rubric wording.
TODO_RE = re.compile(r"\bTODO\b|보강하세요|scaffold", re.IGNORECASE)

GENERIC_ALIAS_EXACT = {
    "시스템",
    "조건",
    "판단",
    "답안",
    "내용",
    "정의",
    "설명",
    "문제",
    "개선",
    "response",
    "system",
    "condition",
    "answer",
    "k",
    "K",
}

MIN_ROUTING_ALIASES = 5
MIN_ROUTING_FIELD_POINTS = 5
MIN_FACT_ANCHORS = 3


def _project_root() -> Path:
    here = Path(__file__).resolve()
    candidates = [
        here.parents[1],
        Path.cwd(),
        Path("/workspace/prof_eng_answer"),
    ]

    for candidate in candidates:
        if (candidate / "rubrics" / "topic_packs").exists():
            return candidate

    raise SystemExit("ERROR: project root not found. Run from prof_eng_answer repo.")


def _read_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise ValueError(f"invalid JSON: {path}: {exc}") from exc


def _list_strings(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def _has_todo_text(value: Any) -> bool:
    if isinstance(value, dict):
        return any(_has_todo_text(v) for v in value.values())
    if isinstance(value, list):
        return any(_has_todo_text(v) for v in value)
    if isinstance(value, str):
        return bool(TODO_RE.search(value))
    return False


def _topic_pack_dirs(root: Path, topic_id: str | None) -> list[Path]:
    base = root / "rubrics" / "topic_packs"

    if topic_id:
        path = base / topic_id
        if not path.exists():
            raise SystemExit(f"ERROR: topic pack not found: {path}")
        return [path]

    return sorted(path for path in base.iterdir() if path.is_dir())


def _validate_required_files(pack_dir: Path, errors: list[str], warnings: list[str]) -> None:
    for filename in REQUIRED_FILES:
        path = pack_dir / filename
        if not path.exists():
            errors.append(f"{pack_dir.name}: missing required file: {filename}")

    for filename in OPTIONAL_FILES:
        path = pack_dir / filename
        if not path.exists():
            warnings.append(f"{pack_dir.name}: optional file missing: {filename}")


def _validate_no_todo(pack_dir: Path, errors: list[str]) -> None:
    for path in pack_dir.iterdir():
        if path.name not in REQUIRED_FILES + OPTIONAL_FILES:
            continue

        if path.suffix == ".json":
            try:
                data = _read_json(path)
            except ValueError as exc:
                errors.append(str(exc))
                continue
            if _has_todo_text(data):
                errors.append(f"{pack_dir.name}: TODO/scaffold placeholder remains in {path.name}")
        elif path.name == "README.md":
            text = path.read_text(encoding="utf-8", errors="replace")
            # README generated by scaffold contains checklist text. That is useful
            # in a draft, but reviewed topic packs should remove scaffold wording.
            if TODO_RE.search(text):
                errors.append(f"{pack_dir.name}: TODO/scaffold placeholder remains in {path.name}")


def _validate_topic_id(data: dict[str, Any], expected_topic_id: str, file_label: str, errors: list[str]) -> None:
    actual = data.get("topic_id")
    if actual != expected_topic_id:
        errors.append(
            f"{expected_topic_id}: topic_id mismatch in {file_label}: "
            f"expected={expected_topic_id}, actual={actual}"
        )


def _validate_model_answer(pack_dir: Path, errors: list[str], warnings: list[str], strict_generic: bool) -> None:
    topic_id = pack_dir.name
    path = pack_dir / "model_answer.json"
    if not path.exists():
        return

    try:
        data = _read_json(path)
    except ValueError as exc:
        errors.append(str(exc))
        return

    _validate_topic_id(data, topic_id, "model_answer.json", errors)

    title = data.get("title") or data.get("title_ko") or data.get("name")
    if not isinstance(title, str) or not title.strip():
        errors.append(f"{topic_id}: model_answer.json missing title/title_ko/name")

    question_examples = _list_strings(data.get("question_examples"))
    expected_question_patterns = _list_strings(data.get("expected_question_patterns"))
    if not question_examples and not expected_question_patterns:
        warnings.append(
            f"{topic_id}: model_answer.json has no question_examples/expected_question_patterns"
        )

    routing_aliases = _list_strings(data.get("routing_aliases"))
    routing_field_points = _list_strings(data.get("routing_field_points"))

    if len(set(routing_aliases)) < MIN_ROUTING_ALIASES:
        errors.append(
            f"{topic_id}: routing_aliases too few: "
            f"{len(set(routing_aliases))} < {MIN_ROUTING_ALIASES}"
        )

    if len(set(routing_field_points)) < MIN_ROUTING_FIELD_POINTS:
        errors.append(
            f"{topic_id}: routing_field_points too few: "
            f"{len(set(routing_field_points))} < {MIN_ROUTING_FIELD_POINTS}"
        )

    generic_aliases = sorted({alias for alias in routing_aliases if alias.strip() in GENERIC_ALIAS_EXACT})
    if generic_aliases:
        message = f"{topic_id}: generic routing aliases found: {generic_aliases}"
        if strict_generic:
            errors.append(message)
        else:
            warnings.append(message)

    if not _list_strings(data.get("high_score_points")) and not _list_strings(data.get("high_score_features")):
        errors.append(f"{topic_id}: model_answer.json missing high_score_points/high_score_features")

    if not _list_strings(data.get("common_missing_points")) and not _list_strings(data.get("low_score_patterns")):
        warnings.append(f"{topic_id}: model_answer.json missing common_missing_points/low_score_patterns")


def _validate_fact_anchor(pack_dir: Path, errors: list[str], warnings: list[str]) -> None:
    topic_id = pack_dir.name
    path = pack_dir / "fact_anchor.json"
    if not path.exists():
        return

    try:
        data = _read_json(path)
    except ValueError as exc:
        errors.append(str(exc))
        return

    _validate_topic_id(data, topic_id, "fact_anchor.json", errors)

    anchors = data.get("anchors")
    if not isinstance(anchors, list):
        errors.append(f"{topic_id}: fact_anchor.json anchors must be a list")
        return

    if len(anchors) < MIN_FACT_ANCHORS:
        errors.append(f"{topic_id}: too few fact anchors: {len(anchors)} < {MIN_FACT_ANCHORS}")

    seen_ids: set[str] = set()
    for idx, anchor in enumerate(anchors, start=1):
        if not isinstance(anchor, dict):
            errors.append(f"{topic_id}: anchor #{idx} must be object")
            continue

        anchor_id = anchor.get("anchor_id")
        if not isinstance(anchor_id, str) or not anchor_id.strip():
            errors.append(f"{topic_id}: anchor #{idx} missing anchor_id")
        elif anchor_id in seen_ids:
            errors.append(f"{topic_id}: duplicate anchor_id: {anchor_id}")
        else:
            seen_ids.add(anchor_id)

        statement = anchor.get("statement") or anchor.get("expected")
        if not isinstance(statement, str) or not statement.strip():
            errors.append(f"{topic_id}: anchor #{idx} missing statement/expected")

        keywords = anchor.get("keywords")
        if keywords is not None and not isinstance(keywords, list):
            warnings.append(f"{topic_id}: anchor #{idx} keywords should be list")


def _validate_topic_importance(pack_dir: Path, errors: list[str], warnings: list[str]) -> None:
    topic_id = pack_dir.name
    path = pack_dir / "topic_importance.json"
    if not path.exists():
        return

    try:
        data = _read_json(path)
    except ValueError as exc:
        errors.append(str(exc))
        return

    _validate_topic_id(data, topic_id, "topic_importance.json", errors)

    for key in ["difficulty", "selection_importance"]:
        value = data.get(key)
        if not isinstance(value, str) or not value.strip():
            errors.append(f"{topic_id}: topic_importance.json missing {key}")

    band = data.get("excellent_score_band")
    if band is not None:
        if (
            not isinstance(band, list)
            or len(band) != 2
            or not all(isinstance(v, (int, float)) for v in band)
        ):
            warnings.append(f"{topic_id}: excellent_score_band should be [min, max]")


def _validate_logic_check(pack_dir: Path, errors: list[str], warnings: list[str], require_logic: bool) -> None:
    topic_id = pack_dir.name
    path = pack_dir / "logic_check.json"

    if not path.exists():
        if require_logic:
            errors.append(f"{topic_id}: logic_check.json required but missing")
        else:
            warnings.append(f"{topic_id}: logic_check.json missing; allowed for easy/simple topics")
        return

    try:
        data = _read_json(path)
    except ValueError as exc:
        errors.append(str(exc))
        return

    _validate_topic_id(data, topic_id, "logic_check.json", errors)

    deterministic = data.get("deterministic_checks")
    if not isinstance(deterministic, dict):
        errors.append(f"{topic_id}: logic_check.json deterministic_checks must be object")
        return

    aliases = _list_strings(deterministic.get("topic_aliases"))
    if not aliases:
        warnings.append(f"{topic_id}: logic_check deterministic_checks.topic_aliases empty")

    for key in ["fatal_checks", "major_checks"]:
        value = deterministic.get(key)
        if value is not None and not isinstance(value, list):
            errors.append(f"{topic_id}: deterministic_checks.{key} must be list")


def validate_topic_pack(pack_dir: Path, args: argparse.Namespace) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []

    _validate_required_files(pack_dir, errors, warnings)

    # If required files are missing, skip deeper validation for clarity.
    if errors:
        return errors, warnings

    _validate_no_todo(pack_dir, errors)
    _validate_model_answer(pack_dir, errors, warnings, args.strict_generic_aliases)
    _validate_fact_anchor(pack_dir, errors, warnings)
    _validate_topic_importance(pack_dir, errors, warnings)
    _validate_logic_check(pack_dir, errors, warnings, args.require_logic_check)

    return errors, warnings


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Validate topic_pack authoring quality.")
    parser.add_argument("--topic-id", default=None, help="validate one topic pack only")
    parser.add_argument(
        "--strict-generic-aliases",
        action="store_true",
        help="treat exact generic routing aliases as errors instead of warnings",
    )
    parser.add_argument(
        "--require-logic-check",
        action="store_true",
        help="require logic_check.json for all validated topic packs",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="print only summary and failures",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    root = _project_root()
    pack_dirs = _topic_pack_dirs(root, args.topic_id)

    all_errors: list[str] = []
    all_warnings: list[str] = []

    if not args.quiet:
        print("RUN: scripts/validate_topic_pack_quality.py")

    for pack_dir in pack_dirs:
        errors, warnings = validate_topic_pack(pack_dir, args)
        all_errors.extend(errors)
        all_warnings.extend(warnings)

        if not args.quiet:
            status = "FAIL" if errors else "OK"
            print(f"{status}: {pack_dir.name}")

            for warning in warnings:
                print("  WARN:", warning)

            for error in errors:
                print("  ERROR:", error)

    print()
    if all_errors:
        print("INVALID: topic pack quality")
    else:
        print("VALID: topic pack quality")

    print("packs:", len(pack_dirs))
    print("errors:", len(all_errors))
    print("warnings:", len(all_warnings))

    if all_errors:
        print()
        print("ERRORS:")
        for error in all_errors:
            print("-", error)

    return 1 if all_errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
